export const popularEvents = [
    {
        id: 1,
        img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dpc/social_ti10.jpg",
        title: "Dota TI",
        date: "August 14, 2023",
        time: "2 PM",
        location: "Cebu",
        price: "Free",
        link: "#",
    },
    {
        id: 2,
        img: "https://cdn.neowin.com/news/images/uploaded/2023/07/1688839676_banner-twitchcon-2023.jpg",
        title: "Twitch Con",
        date: "December 24, 2023",
        time: "3 AM",
        location: "Manila",
        price: "Free",
        link: "#",
    },
    {
        id: 3,
        img: "https://www.pinnacle.com/Cms_Data/Contents/Guest/Media/esports2017/Article-Images/CSGO/2022/2022-PGL-Major-Antwerp-articles/Plain-background-PGL-Logo-Pinnacle-In-case-we-need-to-do-ad-hoc-stuff-Article.jpg",
        title: "CS Majors",
        date: "November 5, 2023",
        time: "5 PM",
        location: "Davao",
        price: "Free",
        link: "#",
    },
    {
        id: 4,
        img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dpc/social_ti10.jpg",
        title: "Dota TI",
        date: "August 14, 2023",
        time: "2 PM",
        location: "Cebu",
        price: "Free",
        link: "#",
    },
    {
        id: 5,
        img: "https://cdn.neowin.com/news/images/uploaded/2023/07/1688839676_banner-twitchcon-2023.jpg",
        title: "Twitch Con",
        date: "December 24, 2023",
        time: "3 AM",
        location: "Manila",
        price: "Free",
        link: "#",
    },
    {
        id: 6,
        img: "https://www.pinnacle.com/Cms_Data/Contents/Guest/Media/esports2017/Article-Images/CSGO/2022/2022-PGL-Major-Antwerp-articles/Plain-background-PGL-Logo-Pinnacle-In-case-we-need-to-do-ad-hoc-stuff-Article.jpg",
        title: "CS Majors",
        date: "November 5, 2023",
        time: "5 PM",
        location: "Davao",
        price: "Free",
        link: "#",
    },
    {
        id: 7,
        img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dpc/social_ti10.jpg",
        title: "Dota TI",
        date: "August 14, 2023",
        time: "2 PM",
        location: "Cebu",
        price: "Free",
        link: "#",
    },
    {
        id: 8,
        img: "https://cdn.neowin.com/news/images/uploaded/2023/07/1688839676_banner-twitchcon-2023.jpg",
        title: "Twitch Con",
        date: "December 24, 2023",
        time: "3 AM",
        location: "Manila",
        price: "Free",
        link: "#",
    },
    {
        id: 9,
        img: "https://www.pinnacle.com/Cms_Data/Contents/Guest/Media/esports2017/Article-Images/CSGO/2022/2022-PGL-Major-Antwerp-articles/Plain-background-PGL-Logo-Pinnacle-In-case-we-need-to-do-ad-hoc-stuff-Article.jpg",
        title: "CS Majors",
        date: "November 5, 2023",
        time: "5 PM",
        location: "Davao",
        price: "Free",
        link: "#",
    },
    {
        id: 10,
        img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dpc/social_ti10.jpg",
        title: "Dota TI",
        date: "August 14, 2023",
        time: "2 PM",
        location: "Cebu",
        price: "Free",
        link: "#",
    },
    {
        id: 11,
        img: "https://cdn.neowin.com/news/images/uploaded/2023/07/1688839676_banner-twitchcon-2023.jpg",
        title: "Twitch Con",
        date: "December 24, 2023",
        time: "3 AM",
        location: "Manila",
        price: "Free",
        link: "#",
    },
    {
        id: 12,
        img: "https://www.pinnacle.com/Cms_Data/Contents/Guest/Media/esports2017/Article-Images/CSGO/2022/2022-PGL-Major-Antwerp-articles/Plain-background-PGL-Logo-Pinnacle-In-case-we-need-to-do-ad-hoc-stuff-Article.jpg",
        title: "CS Majors",
        date: "November 5, 2023",
        time: "5 PM",
        location: "Davao",
        price: "Free",
        link: "#",
    }
]
